language: scala
scala:
  - 2.13.2

services:
  - xvfb

env:
  - DISPLAY=:99.0

before_script:
  - curl --create-dirs -L -o $HOME/.sbt/launchers/0.13.10/sbt-launch.jar https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.10/sbt-launch.jar

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls
