version: "3.9"

services:
  player:
    build:
      context: .
      dockerfile: Player/Dockerfile
    ports:
    - "9001:9001"
  fileio:
    build:
      context: .
      dockerfile: FileIO/Dockerfile
    ports:
    - "9002:9002"
    volumes:
    - .:/gameSaves
  root:
    build: .
    ports:
    - "9000:9000"
    depends_on:
      - player
      - fileio