version: "3.9"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MILL
      MYSQL_DATABASE: mill
      MYSQL_USER: mill
      MYSQL_PASSWORD: mill
    volumes:
      - .:/var/lib/mill

  player:
    build:
      context: ./Player
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db:3306

  fileio:
    build:
      context: ./FileIO
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db:3306
    volumes:
      - .:/gameSaves

  root:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - player
      - fileio
    environment:
      - PLAYERHTTPSERVER=player:8081
      - FILEIOHTTPSERVER=fileio:8082